# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporteador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Soporteador', models.CharField(blank=True, max_length=50, null=True)),
                ('Apellido_Paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('Apellido_Materno', models.CharField(blank=True, max_length=50, null=True)),
                ('Edad', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('Especialidad_de_Soporte', models.CharField(blank=True, max_length=50, null=True)),
                ('Foto', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
