# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160915_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_soporte',
            field=models.BooleanField(default=False),
        ),
    ]
