# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_soporte',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
