# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160915_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_soporte',
        ),
    ]
